Sign up and approve accounts pages
mysociety/local-intelligence-hub pull request #220
Opened 2023-03-22 16:22 UTC by struan

This adds pages to allow a user to request and account and an admin to approve those newly created accounts.

Fixes #217 
Fixes #216

2023-03-29 09:43 UTC, zarino requested changes
Generally looks good. A few thoughts:

- Signup page (well, all account-request-related pages) need to be accessible without being logged in, which isn’t currently the case.
- Reviewers might not be able to recognise people from their email address and organisation alone, so we probably want to collect the person’s name during signup, and expose that to the reviewer on `/activate_accounts`.
- Not related to this PR, but it’s confusing that the box you type your _email address_ into on the `/accounts/login` page is labelled "Username". We ask people for their "Email" on `/accounts/signup`, we should ask for the same on `/accounts/login`.
- If a user attempts to log in with their new details _before_ their account is approved, they get a generic "Please enter a correct username and password" error at `/accounts/login`. Is there any way we could detect that they’re trying to log into an un-approved account, and show a message like "Your account hasn’t been approved yet" instead?

2023-03-30 14:51 UTC, zarino requested changes

2023-04-03 17:00 UTC, struan commented on hub/templates/hub/accounts/activate_accounts.html
> +                            {{ user_form.instance.first_name }} {{ user_form.instance.last_name }}
done

2023-04-03 17:00 UTC, struan commented
OK, I think I've resolved all the issues with this.

2023-04-12 10:48 UTC, zarino approved these changes
@struan this looks good to me! I’ve added a couple of commits to the end. If you’re happy with them, feel free to merge.

2023-04-12 13:47 UTC, merged