Display filter values in map tooltips
mysociety/local-intelligence-hub pull request #287
Opened 2023-06-28 16:19 UTC by struan

Fixes #207

2023-07-06 16:22 UTC, zarino requested changes
Generally good. I’ve left a couple of comments about tooltip content styling.

2023-07-06 16:22 UTC, zarino commented on hub/static/js/explore.esm.js
> +                text += p + ": " + props[p] + "<br>"
If `props[p]` is a float, we should format it to a sensible number of decimal places…

<img width="403" alt="Screenshot 2023-07-06 at 17 15 38" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/5ee9210f-88d1-472a-965c-abaff0a6179f">

And we should also show "%" after it, if it’s a percentage.

2023-07-06 16:22 UTC, zarino commented on hub/static/js/explore.esm.js
> +                text += p + ": " + props[p] + "<br>"
More generally, I wonder whether we could override the styling in this tooltip, to make it feel more like the rest of the site – `font-size: var(--bs-body-font-size)` and `font-family: var(--bs-body-font-family)` on `.leaflet-tooltip` might do it?

2023-07-06 16:22 UTC, zarino commented on hub/static/js/explore.esm.js
> +                text += p + ": " + props[p] + "<br>"
Finally, I wonder whether a table layout in here might make it easier to scan down the list of numbers? I’m just thinking, when you have a few datasets active, it’s like a game of hide and seek trying to parse the numbers from each line, whereas a table layout would force the numbers into a neat column down the right-hand side.

2023-07-17 16:42 UTC, zarino approved these changes
@struan I’ve added a fixup commit with some styling improvements. I think this is good to go from my perspective.

It’d be nice if the table _also_ appeared in the tooltip when you’re hovering over constituencies that _don’t_ match the given filters (so you could see _why_ they’ve not matched) but I have a feeling that will be a much bigger job that requires a change in how `explore.json` returns features. So maybe something to tackle as a separate change.

2023-07-18 14:34 UTC, merged

2023-07-18 14:38 UTC, struan commented
I've added ticket #297 to capture adding the same data to excluded areas.