DATASET: RSPB nature reserves
mysociety/local-intelligence-hub pull request #376
Opened 2023-12-21 16:27 UTC by alexander-griffen

Note: Dataset csv in the shared drive - made in QGIS by finding the centroids of each reserve, then reprojecting the data into a projection that lines up the points as lat/long coordinates

2024-01-09 10:02 UTC, struan requested changes
one big question, and a few small improvements/nit picks.

Also, one fixup for linting.

2024-01-09 10:02 UTC, struan commented on hub/management/commands/import_rspb_nature_reserves.py
> +                "category": "place",
I wonder if this makes more sense as a movement thing, and also have a second data set with the names of the reserves a la national trust?

2024-01-10 12:33 UTC, struan commented on hub/management/commands/import_rspb_nature_reserves.py
> +                "is_filterable": False,
one other thing is this should have the unit_type and unit_distribution attributes :)

2024-01-16 12:08 UTC, alexander-griffen commented on hub/management/commands/import_rspb_nature_reserves.py
> +    def add_arguments(self, parser):
Django complains if I remove the `handle()` method, so I have kept that, and removed the other lines of code from this point on

2024-01-18 15:56 UTC, struan commented
One small question here is that looking at the centroids csv I notice that some of the entries in there are "Non-Publicised Reserve". I'm not sure what that means here and if it means we should not be putting them on the site? Or at least not listing the names?

2024-01-18 15:57 UTC, struan approved these changes
Module one question in the comments this looks good.

2024-01-22 13:46 UTC, merged