Import and display action scorecards scores for local councils
mysociety/local-intelligence-hub pull request #531
Opened 2024-04-17 13:41 UTC by struan

Splits it into two datasets: total and section scores. 
Updates the area template to allow range related datasets.

Fixes #514

<img width="427" alt="Screenshot 2024-04-17 at 14 39 24" src="https://github.com/mysociety/local-intelligence-hub/assets/5310/4949dc53-5301-4072-942f-9b820ec1c1fc">

2024-04-17 13:42 UTC, struan commented
Not clear if the chart needs a title, possibly so.

2024-04-18 09:41 UTC, zarino requested changes
This looks generally ok to me. Three points:

- Ideally, rather than comparing to a "UK average", we’d compare to all councils of the current council’s "type". But I expect there’s no way to easily do that right now. So, as a minimum, I think we should hide the "UK average" stuff _everywhere_ in relation to this data (so, on the area page card, and on the Explore page) – both because comparisons to the average mean less when different councils have different powers/responsibilities (and even different maximum possible scores per section) and we _also_ said to council officers, in the run-up to the Scorecards, that we wouldn’t facilitate comparisons outside a council’s "type".
- On the area page card, my instinct is a table (without the `js-chart` class) would be easier to read than a chart. What do you think?
- I’d title the card "Council Climate Action Scorecard" rather than "Action Scorecards overall score"

2024-04-22 09:52 UTC, struan commented
Tweaked:

<img width="431" alt="Screenshot 2024-04-22 at 10 52 40" src="https://github.com/mysociety/local-intelligence-hub/assets/5310/49fcc1e4-85fd-486f-8956-69120bc21423">

2024-04-22 09:58 UTC, zarino requested changes
Two quick comments on things I’ve just noticed (sorry!)

I also wonder what’s going on with the rounding in your screenshot?

<img width="808" alt="Screenshot 2024-04-22 at 10 58 24" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/1ae9e3a5-12ee-4694-836b-e67ec5ffa408">

2024-04-22 09:58 UTC, zarino commented on hub/management/commands/import_council_scorecards_score.py
> +        "source_label": "Data from the Climate Emergency UK.",
Drop the "the" 😉

2024-04-22 09:58 UTC, zarino commented on hub/management/commands/import_council_scorecards_score.py
> +        "source": "https://councilclimatescorecards.uk/",
I wonder, could we make this a direct link to the council’s page on the scorecards site? At least that way, there’ll be a direct link to more detail from the dataset card on the area page.

2024-04-24 09:13 UTC, merged